/*
description
ƒe[ƒuƒ‹‚ðíœ‚·‚é
author
client
*/
--sql
BEGIN TRY
    BEGIN TRANSACTION
        DELETE FROM [Test].[dbo].[User]
    COMMIT TRANSACTION
END TRY

BEGIN CATCH
    ROLLBACK TRANSACTION
    PRINT ERROR_MESSAGE()
    PRINT 'ROLLBACK TRANSACTION'
END CATCH
